export interface Product {
  id: string
  name: string
  price: number
  unit_price: number
  unit: string
  image: string
  category: string
  subcategory?: string
  description: string
  inStock: boolean
  isBestseller?: boolean
  isNew?: boolean
  pieces: number
}

export interface Category {
  name: string
  slug: string
  description: string
  icon: string
  color: string
}

export const shopInfo = {
  name: 'Mirus Mix',
  owner: 'Martin Magnberg',
  phone: '+49 (0)6203-64668',
  description: 'Zahnarzt-Praxisbedarf: Kinderzugabeartikel, Prophylaxebedarf, Recall-Karten und mehr',
  logo: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/MediaGallery/design_2017/header/logo_mirus_mix_green_blue_transparent_small.png',
  email: 'info@mirus-mix.de',
  address: 'Deutschland',
}

export const categories: Category[] = [
  {
    name: 'Kinderzugabeartikel',
    slug: 'kinderzugabeartikel',
    description: 'Tolle Überraschungen für kleine Patienten – Ringe, Springbälle, Dinosaurier und mehr',
    icon: '🎁',
    color: 'from-pink-400 to-purple-500',
  },
  {
    name: 'Praxis- & Prophylaxebedarf',
    slug: 'praxis-prophylaxebedarf',
    description: 'Professionelle Hilfsmittel für Ihre Zahnarztpraxis – Sanduhr, Zahnspiegel, Behälter',
    icon: '🦷',
    color: 'from-sky-400 to-blue-500',
  },
  {
    name: 'Karten',
    slug: 'karten',
    description: 'Recall-Postkarten und Einladungskarten für Ihre Patienten',
    icon: '📬',
    color: 'from-emerald-400 to-teal-500',
  },
  {
    name: 'Bestseller',
    slug: 'bestseller',
    description: 'Unsere beliebtesten Produkte – von Zahnärzten am häufigsten bestellt',
    icon: '⭐',
    color: 'from-amber-400 to-orange-500',
  },
]

const PLACEHOLDER = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjQwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZTBmMmZlIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtc2l6ZT0iNjQiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGRvbWluYW50LWJhc2VsaW5lPSJtaWRkbGUiPvCfpoA8L3RleHQ+PC9zdmc+'

export const products: Product[] = [
  {
    id: '116',
    name: 'Ringe mit kleinen Kristallen',
    price: 24.90,
    unit_price: 0.35,
    unit: 'Stück',
    pieces: 72,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8C/FD5C/1DA2/C354/2F59/C0A8/29BA/0994/Ring_med_rulle_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Schmuck/Ringe',
    description: 'Funkelnde Ringe mit kleinen Kristallen – perfekte Überraschung für kleine Patientinnen nach der Behandlung. Bunt sortiert, hochwertige Qualität.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '124',
    name: 'Radierer Bleistiftstecker Smilies',
    price: 22.90,
    unit_price: 0.32,
    unit: 'Stück',
    pieces: 72,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8D/011F/5C1F/D004/DF54/C0A8/29B9/827E/Bleistiftstecker_Smilies_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Themen & Trends',
    description: 'Niedliche Radierer als Bleistiftstecker mit Smiley-Motiv. Praktisch und beliebt bei Kindern jeden Alters – ideal als Zugabe nach der Behandlung.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '200',
    name: 'Sanduhr',
    price: 26.90,
    unit_price: 0.67,
    unit: 'Stück',
    pieces: 40,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8D/0470/4FA7/82CE/64A2/C0A8/29B9/6669/200_Sanduhr_m.jpg',
    category: 'praxis-prophylaxebedarf',
    subcategory: 'Sanduhr/Spiegel',
    description: 'Klassische Sanduhr für die empfohlene Zahnputzzeit von 2 Minuten. Motiviert Kinder zum gründlichen Zähneputzen. Stabile Qualität, bunt gemischt.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '202',
    name: 'Sanduhr Smile-Top 2 Farben Mix',
    price: 28.90,
    unit_price: 0.72,
    unit: 'Stück',
    pieces: 40,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4D32/AAB1/46C7/7833/5FCB/C0A8/29B9/FE2C/202_Sanduhr_Smilie_top_1_m.jpg',
    category: 'praxis-prophylaxebedarf',
    subcategory: 'Sanduhr/Spiegel',
    description: 'Sanduhr mit Smile-Top in 2 fröhlichen Farben – macht das Zähneputzen zum Erlebnis. Ideal als Mitgabe für Ihre kleinen Patienten.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '231',
    name: 'Zahnspiegel',
    price: 22.90,
    unit_price: 0.38,
    unit: 'Stück',
    pieces: 60,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8E/11EC/E3E4/7F40/0A29/C0A8/29B9/6B0A/231_Zahnspiegel_1_m.jpg',
    category: 'praxis-prophylaxebedarf',
    subcategory: 'Sanduhr/Spiegel',
    description: 'Handlicher Zahnspiegel zur spielerischen Mundhygiene-Kontrolle. Perfekt für das Prophylaxe-Set Ihrer Praxis. Stabile Ausführung, für Kinder geeignet.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '239',
    name: 'Stempel Zahn',
    price: 22.90,
    unit_price: 0.38,
    unit: 'Stück',
    pieces: 60,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8E/1B29/C965/A717/AF5D/C0A8/29B9/68DE/239_Stempel_Zahn_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Themen & Trends',
    description: 'Lustiger Stempel mit Zahnmotiv – Kinder lieben es zu stempeln! Tolle Zugabe, die gleichzeitig das Zahn-Bewusstsein fördert.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '249',
    name: 'Steck-Buntstifte',
    price: 26.90,
    unit_price: 0.54,
    unit: 'Stück',
    pieces: 50,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8E/1D7B/C44B/2090/D381/C0A8/29BA/DD5E/Steck-Buntstifte_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Themen & Trends',
    description: 'Praktische Steck-Buntstifte in leuchtenden Farben – kreativ und lehrreich zugleich. Beliebt bei Kindern aller Altersgruppen.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '252',
    name: 'Glitzertiere',
    price: 26.90,
    unit_price: 0.28,
    unit: 'Stück',
    pieces: 96,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8E/1DCD/6E17/2EF2/3F9D/C0A8/29B9/77FE/Glitzertiere_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Tiere/Plüsch',
    description: 'Funkelnde Glitzertiere in verschiedenen Formen und Farben. Kinder sind begeistert – machen die Zahnarztbehandlung zu einem positiven Erlebnis.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '254',
    name: 'Dinosaurier',
    price: 29.90,
    unit_price: 0.21,
    unit: 'Stück',
    pieces: 144,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8E/1E00/6464/41BA/2B2F/C0A8/29B9/8840/254_Dinosaurier_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Tiere/Plüsch',
    description: 'Mini-Dinosaurier aus robustem Kunststoff – jedes Kind liebt Dinos! Ideal als Überraschung nach dem Zahnarztbesuch. Verschiedene Arten gemischt.',
    inStock: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: '264',
    name: 'Zahnbehälter Happy Smile',
    price: 19.90,
    unit_price: 0.55,
    unit: 'Stück',
    pieces: 36,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4C8E/1E8E/1682/D7BE/502D/C0A8/29BA/ED8C/Zahnbehaelter_Happy_Smile_m.jpg',
    category: 'praxis-prophylaxebedarf',
    subcategory: 'Behälter',
    description: 'Niedlicher Zahnbehälter mit Happy-Smile-Motiv – ideal zum Aufbewahren ausgefallener Zähne. Kinder freuen sich über diese tolle Erinnerung.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '299',
    name: 'Springbälle Smile (30mm)',
    price: 24.90,
    unit_price: 0.25,
    unit: 'Stück',
    pieces: 100,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/57D6/6638/B930/5058/EAF9/C0A8/2BBC/98D4/Smilie_Flumies_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Bälle & Springbälle',
    description: 'Bunte Springbälle mit Smiley-Motiv, 30mm Durchmesser. Kinder lieben das Hüpfen! Tolle Belohnung nach dem Zahnarztbesuch – macht Lust auf mehr.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '325',
    name: 'Mini-Zahnbehälter',
    price: 22.90,
    unit_price: 0.32,
    unit: 'Stück',
    pieces: 72,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4FE1/8280/7504/337D/87EB/C0A8/2981/C36E/325_Mini_Zahnbehaelter_m.png',
    category: 'praxis-prophylaxebedarf',
    subcategory: 'Behälter',
    description: 'Kompakter Mini-Zahnbehälter zum Aufbewahren von Milchzähnen. Praktisch, hygienisch und mit freundlichem Design – Kinder lieben ihn.',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '360',
    name: 'Schatzkammer Mix',
    price: 46.90,
    unit_price: 0.31,
    unit: 'Stück',
    pieces: 150,
    image: 'https://www.mirus-mix.de/WebRoot/Store12/Shops/62584053/4DFA/1204/2400/F8BB/42D3/C0A8/29BA/F163/Schatzkammermix_150_Stueck_m.jpg',
    category: 'kinderzugabeartikel',
    subcategory: 'Alle Artikel',
    description: 'Die ultimative Schatzkammer mit 150 gemischten Überraschungsartikeln – Ringe, Tiere, Bälle und mehr. Perfekt für Praxen mit vielen kleinen Patienten.',
    inStock: true,
    isBestseller: true,
    isNew: false,
  },
  {
    id: '527',
    name: 'Tattoos Boys',
    price: 19.90,
    unit_price: 0.14,
    unit: 'Stück',
    pieces: 144,
    image: PLACEHOLDER,
    category: 'kinderzugabeartikel',
    subcategory: 'Sticker/Tattoos',
    description: 'Coole Abzieh-Tattoos speziell für Jungs – Autos, Tiere, Superhelden und mehr. Einfach aufzutragen, leicht abzuwaschen. Kinder sind begeistert!',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '528',
    name: 'Tattoos Girls',
    price: 19.90,
    unit_price: 0.14,
    unit: 'Stück',
    pieces: 144,
    image: PLACEHOLDER,
    category: 'kinderzugabeartikel',
    subcategory: 'Sticker/Tattoos',
    description: 'Hübsche Abzieh-Tattoos für kleine Mädchen – Blumen, Schmetterlinge, Einhorn und mehr. Einfach aufzutragen, leicht abzuwaschen. Kinder sind begeistert!',
    inStock: true,
    isBestseller: true,
  },
  {
    id: '402',
    name: 'Antistress Zahn',
    price: 24.90,
    unit_price: 1.04,
    unit: 'Stück',
    pieces: 24,
    image: PLACEHOLDER,
    category: 'kinderzugabeartikel',
    subcategory: 'Themen & Trends',
    description: 'Lustiger Antistress-Ball in Zahnform – zum Kneten und Quetschen. Ideal als Spielzeug für die Wartezimmer-Zeit. Tolle Zugabe nach der Behandlung.',
    inStock: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: '285',
    name: 'Radierer Milchzähne',
    price: 24.90,
    unit_price: 0.35,
    unit: 'Stück',
    pieces: 72,
    image: PLACEHOLDER,
    category: 'kinderzugabeartikel',
    subcategory: 'Themen & Trends',
    description: 'Süße Radierer in Milchzahn-Form – praktisch und thematisch passend für die Zahnarztpraxis. Hochwertige Qualität, gut radierend.',
    inStock: true,
    isBestseller: false,
  },
  {
    id: '585',
    name: 'Schlüsselanhänger Reflektor Zahn',
    price: 19.90,
    unit_price: 0.83,
    unit: 'Stück',
    pieces: 24,
    image: PLACEHOLDER,
    category: 'kinderzugabeartikel',
    subcategory: 'Themen & Trends',
    description: 'Praktischer Schlüsselanhänger in Zahnform mit Reflektor – sicher und stylish! Erhöht die Sichtbarkeit im Straßenverkehr. Tolles Mitbringsel.',
    inStock: true,
    isBestseller: false,
    isNew: true,
  },
  {
    id: '960',
    name: 'Springbälle Happy Zahn (33mm)',
    price: 24.90,
    unit_price: 0.52,
    unit: 'Stück',
    pieces: 50,
    image: PLACEHOLDER,
    category: 'kinderzugabeartikel',
    subcategory: 'Bälle & Springbälle',
    description: 'Springbälle in Zahnform, 33mm – größer und stabiler als Standard-Springbälle. Mit freundlichem Gesicht, macht großen Spaß. Toll für Kinder ab 3 Jahren.',
    inStock: true,
    isBestseller: true,
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Dr. Sandra Hoffmann',
    practice: 'Zahnarztpraxis Hoffmann, München',
    rating: 5,
    text: 'Wir bestellen seit über 5 Jahren bei Mirus Mix und sind absolut begeistert. Die Kinder freuen sich immer riesig über die Zugabeartikel nach der Behandlung. Qualität und Service sind top!',
    avatar: '👩‍⚕️',
  },
  {
    id: 2,
    name: 'Zahnarzt Michael Berger',
    practice: 'Gemeinschaftspraxis am Marktplatz, Hamburg',
    rating: 5,
    text: 'Die Sanduhren und Zahnspiegel sind bei unseren kleinen Patienten sehr beliebt. Die Preise sind fair und die Lieferung kommt immer pünktlich. Klare Weiterempfehlung!',
    avatar: '👨‍⚕️',
  },
  {
    id: 3,
    name: 'MFA Claudia Schmidt',
    practice: 'Kieferorthopädie Dr. Klein, Frankfurt',
    rating: 5,
    text: 'Der Schatzkammer-Mix ist unser absoluter Favorit! Die Kinder können sich selbst etwas aussuchen – das macht den Zahnarztbesuch gleich viel weniger beängstigend. Super Produkt!',
    avatar: '👩‍💼',
  },
]

export const benefits = [
  {
    icon: '🎁',
    title: 'Riesige Auswahl',
    description: 'Über 200 verschiedene Kinderzugabeartikel und Prophylaxebedarf für Ihre Zahnarztpraxis',
  },
  {
    icon: '💰',
    title: 'Faire Preise',
    description: 'Günstige Stückpreise ab 0,14 € – attraktive Mengenrabatte für regelmäßige Bestellungen',
  },
  {
    icon: '🚀',
    title: 'Schnelle Lieferung',
    description: 'Versand innerhalb von 1–2 Werktagen direkt in Ihre Praxis – zuverlässig und pünktlich',
  },
  {
    icon: '🤝',
    title: 'Persönlicher Service',
    description: 'Kompetente Beratung durch Fachpersonal – wir helfen Ihnen bei der Auswahl der richtigen Artikel',
  },
]
